####################
# CircleCI configuration reference:
#   https://circleci.com/docs/2.0/configuration-reference
####################
#
# This file currently only tests for expiration

version: 2

machine:
  python: 
    version: 2.7.9

####################
# Jobs: see https://circleci.com/docs/2.0/jobs-steps/
####################

jobs:
  build:
    machine: True
      python: 
        version: 2.7.9
    steps:
      - checkout
      - run: pip install bs4 boto
      - run: python alert/expiring.py test
