####################
# CircleCI configuration reference:
#   https://circleci.com/docs/2.0/configuration-reference
####################
#
# This file currently only tests for expiration

version: 2


####################
# Jobs: see https://circleci.com/docs/2.0/jobs-steps/
####################

jobs:
  test:
    machine:
      python:
        version: 2.7.9
    dependencies:
      pre:
        - pip install ansible
    override:
      - ansible-playbook ansible/dev.yml
    steps:
      - checkout
      - run: python alert/expiring.py test
